default: &default
  adapter:  <%= ENV["DB_ADAPTER"] ||= 'postgresql' %>
  database: <%= ENV["DB_DBNAME"] || 'portal' %> 
  host:     <%= ENV["DB_HOSTNAME"] || 'localhost' %>
  pool:     10
  username: <%= ENV["DB_USERNAME"] || 'webdox' %>
  password: <%= ENV["DB_PASSWORD"] || '' %>
  statement_limit: <%= ENV["STATEMENT_LIMIT"] ||= '100' %>

development:
  <<: *default

test:
  <<: *default
  database: <%= "#{ENV['DB_DBNAME']}_test#{ENV['TEST_ENV_NUMBER']}"  %>

production:
  <<: *default
  pool: <%= ENV["DB_POOL"] ||= '32' %>
